### ISSUE TITLE
3G cosumptio is too high

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.beacon.admin.android#25]
As you can see from the screenshot since the 24th of May the app downloaded more than 4 giga from 3G connection. Can you have solve this issue, otherwise the use of the app is really difficult.
![Screenshot_20190604-075435](https://user-images.githubusercontent.com/7909989/58855272-ec117580-869f-11e9-8d3e-bc040027f383.png)

**Comment by Piiit** [comment]
@LucaMiotto tested the app and had no issues with large download sizes or draining battery. It seems fixed with the latest release 0.2.0. @sseppi, Could you please check on your device?

**Comment by Piiit** [comment]
@LucaMiotto @sseppi I never had that issue again, so I will close the issue... if it happens again, please feel free to reopen it.
