### ISSUE TITLE
As not logged user I want to see the whole beacon list in read only mode in order to know where the beacons are located and search for it.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.beacon.admin.android#34]

**Comment by Piiit** [comment]
@sseppi Should this be implemented in this development cycle, or is it a task for future enhancements?

**Comment by sseppi** [comment]
No, this issue is deprecated. We decided to not implement this functionality since the app is dedicated only to the beacon manager who has access to the app.

For this reason I close the issue.
