### ISSUE TITLE
Nearby beacons are not shown, if the authentication token has expired

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.beacon.admin.android#40]
A refresh of that list with pull down should refresh the authentication if expired, it seems (I am not sure) that this gets done only insiede the ALL list.

@noctho @davidebz FYI

**Comment by noctho** [comment]
see https://github.com/noi-techpark/it.bz.beacon.admin.android/issues/41#issuecomment-762725497

**Comment by noctho** [comment]
I cannot confirm your observations. I tested it by setting the token's expire length time on the back end to a short period. Then I tried to refresh after the token was expired and it popped up a dialog with the following message: "Authorization expired. Please log in again!". Then I clicked "OK" and the token was updated.

**Comment by Piiit** [comment]
Works, thanks
