### ISSUE TITLE
List view updates should call the API

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.beacon.admin.android#41]
If we do a swipe down inside the ALL or NEARBY list, the app should do an API call. It seems that it takes the cache sometimes...

@noctho @davidebz FYI

**Comment by noctho** [comment]
I figured out that it refreshes the data only inside ALL. Inside NEAREBE it restarts only the nearby beacon search.

**Comment by noctho** [comment]
fixed, see #43
