### ISSUE TITLE
Install a testing beacon android app alongside the production app

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.beacon.admin.android#42]
Currently we are building a debug release apk to be installed manually on a phone. It has the same application ID assigned, and therefore it overwrites the existing installation from Google Stores...

We should have both apps at the same time with two different IDs and titles, like "Beacons" and "Beacons (Test)"

**Comment by Piiit** [comment]
@noctho Do you know, how I can configure that?

**Comment by davidebz** [comment]
Hi Peter,

in the past I have used the "beta" of the play store. You can upload an apk that only a predefined list of account can upgrade to/install this update but normal users see only the official one. What do you think about this?

**Comment by Piiit** [comment]
@davidebz We used that approach, but at the moment Google needs about 2-3 days to release it, and therefore we build and install apks now manually. However, that is not what I needed here... I do not want to have to reinstall the production application all the time after that I have tested a beta application... So what I want is to test both apps at the same time, the production and testing one, which are also differently configured, talking two different APIs etc.... For the beta/alpha testing we have that approach already on the store... But thanks for your suggestions, normally this would be a good approach... but this case is a bit special (as always) ;-)

**Comment by davidebz** [comment]
Ok! What about to have two distinct mobile phone? One with the official and a second with the beta version to compare functions?

**Comment by noctho** [comment]
If you want to have both apps installed on your phone, you'll need a different package name. I don't know if it works, but you can try to change the package name of the debug android manifest and you can set a different app name there too.

In the build.grade you can somehow define different buildTypes, but I don't know exactly how it works.

**Comment by davidebz** [comment]
Using google I have found

https://www.digitbin.com/install-two-versions-same-app/

changing package should work but you must be sure that the second app does not share resources (i.e. directories) with the official one. This way make me not so happy.

What about search app that allow this? Or really two phones.

**Comment by davidebz** [comment]
Like this app

https://play.google.com/store/apps/details?id=com.lbe.parallel.intl&hl=en

**Comment by Piiit** [comment]
Thx... I will have a look at your proposals...

**Comment by Piiit** [comment]
@davidebz @noctho Done, see my last commit on development https://github.com/noi-techpark/it.bz.beacon.admin.android/commit/e6d01278715e99dd95965deededd3c6d86ed9cfb

For the google services I am not sure thou, the Maps do no longer work... I need to investigate

**Comment by Piiit** [comment]
Maybe we should better do #44 instead of a workaround here for Google Maps... so this issue is solved for now
